fn main() {
    if std::env::var("CARGO_CFG_TARGET_OS").as_deref() == Ok("macos") {
        println!("cargo:rerun-if-changed=src/macos/paste.m");
        println!("cargo:rerun-if-changed=src/macos/remote_capture.m");
        println!("cargo:rerun-if-changed=src/macos/remote_video.m");
        println!("cargo:rerun-if-changed=src/macos/remote_video.h");
        println!("cargo:rerun-if-changed=src/macos/remote_input.m");
        println!("cargo:rerun-if-changed=src/macos/remote_input_lock.m");
        println!("cargo:rerun-if-changed=src/macos/keep_awake.m");
        println!("cargo:rerun-if-changed=src/macos/remote_jpeg.m");
        println!("cargo:rerun-if-changed=src/macos/pinned.m");
        println!("cargo:rerun-if-changed=src/macos/startup.m");
        println!("cargo:rerun-if-changed=src/macos/screen.m");
        println!("cargo:rerun-if-changed=src/macos/recording.m");
        println!("cargo:rerun-if-changed=src/macos/recording_frame.m");
        println!("cargo:rerun-if-changed=src/macos/recording_frame.h");
        println!("cargo:rerun-if-changed=src/macos/recording_audio.m");
        println!("cargo:rerun-if-changed=src/macos/recording_audio.h");
        println!("cargo:rerun-if-changed=src/macos/remote_audio_encoder.h");
        println!("cargo:rerun-if-changed=src/macos/remote_audio_encoder.m");
        println!("cargo:rerun-if-changed=src/macos/remote_audio.m");
        println!("cargo:rerun-if-changed=src/macos/file_assoc.m");
        println!("cargo:rerun-if-changed=src/macos/speaker.m");
        println!("cargo:rerun-if-changed=src/macos/screenshot_legacy.m");
        println!("cargo:rerun-if-changed=src/macos/recording_overlay.h");
        println!("cargo:rerun-if-changed=src/macos/recording_overlay.m");
        println!("cargo:rerun-if-changed=src/macos/video_frames.m");
        println!("cargo:rerun-if-changed=src/macos/rec_trim.m");
        cc::Build::new()
            .file("src/macos/paste.m")
            .file("src/macos/remote_capture.m")
            .file("src/macos/remote_video.m")
            .file("src/macos/remote_audio.m")
            .file("src/macos/remote_audio_encoder.m")
            .file("src/macos/remote_input.m")
            .file("src/macos/remote_input_lock.m")
            .file("src/macos/keep_awake.m")
            .file("src/macos/remote_jpeg.m")
            .file("src/macos/pinned.m")
            .file("src/macos/startup.m")
            .file("src/macos/file_assoc.m")
            .file("src/macos/speaker.m")
            .file("src/macos/screen.m")
            .file("src/macos/screenshot_legacy.m")
            .file("src/macos/recording.m")
            .file("src/macos/recording_frame.m")
            .file("src/macos/recording_audio.m")
            .file("src/macos/recording_overlay.m")
            .file("src/macos/video_frames.m")
            .file("src/macos/rec_trim.m")
            .flag("-fobjc-arc")
            .flag("-mmacosx-version-min=12.0")
            .compile("pastepanda_macos");
        println!("cargo:rustc-link-lib=framework=AppKit");
        println!("cargo:rustc-link-lib=framework=AVFoundation");
        println!("cargo:rustc-link-lib=framework=VideoToolbox");
        println!("cargo:rustc-link-lib=framework=CoreMedia");
        println!("cargo:rustc-link-lib=framework=CoreAudio");
        println!("cargo:rustc-link-lib=framework=CoreServices");
        println!("cargo:rustc-link-lib=framework=CoreVideo");
        println!("cargo:rustc-link-lib=framework=ImageIO");
        println!("cargo:rustc-link-lib=framework=Security");
        println!("cargo:rustc-link-lib=framework=LocalAuthentication");
        println!("cargo:rustc-link-lib=framework=ServiceManagement");
        println!("cargo:rustc-link-lib=framework=IOKit");
        println!("cargo:rustc-link-arg=-Wl,-weak_framework,ScreenCaptureKit");
        println!("cargo:rustc-link-lib=framework=ApplicationServices");
    }
    tauri_build::build()
}
